# Generated by `pnpm deploy:sync`. Edit `deploy/config.ts`, then re-run sync.
# syntax=docker/dockerfile:1

FROM node:22-alpine AS base
RUN corepack enable && corepack prepare pnpm@10.12.1 --activate
WORKDIR /app

FROM base AS deps
COPY package.json pnpm-lock.yaml ./
COPY patches ./patches
# Skip lifecycle scripts: postinstall (fumadocs-mdx) needs source.config.ts
RUN pnpm install --frozen-lockfile --ignore-scripts

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN pnpm rebuild && pnpm run postinstall
RUN pnpm build

FROM base AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
	&& adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=builder /app/patches ./patches
COPY --from=builder /app/next.config.mjs ./next.config.mjs
COPY --from=builder /app/tsconfig.json ./tsconfig.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/migrations ./migrations
COPY --from=builder /app/scripts/db-migrate.mjs ./scripts/db-migrate.mjs
COPY --from=builder /app/drizzle.config.ts ./drizzle.config.ts
COPY --from=builder /app/src/database ./src/database
# fumadocs-mdx createMDX() recompiles source.config.ts into .source and
# remaps docs/framework on every `next start`. Those paths must exist and
# .source must be writable by the non-root runtime user.
COPY --from=builder --chown=nextjs:nodejs /app/source.config.ts ./source.config.ts
COPY --from=builder --chown=nextjs:nodejs /app/.source ./.source
COPY --from=builder --chown=nextjs:nodejs /app/docs/framework ./docs/framework

USER nextjs
EXPOSE 3000

# Migrate at process start (needs DATABASE_URL), then serve Next.js
CMD ["sh", "-c", "pnpm start"]
