/**
 * Regenerates platform deploy files from deploy/config.ts.
 * Run: pnpm deploy:sync
 */
import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { deployConfig } from "./config"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const GENERATED =
    "Generated by `pnpm deploy:sync`. Edit `deploy/config.ts`, then re-run sync."

function write(relPath: string, contents: string) {
    const abs = join(root, relPath)
    mkdirSync(dirname(abs), { recursive: true })
    writeFileSync(abs, contents.endsWith("\n") ? contents : `${contents}\n`)
    console.log(`wrote ${relPath}`)
}

function dockerfile(): string {
    const { port, buildCommand, containerStartCommand } = deployConfig
    return `# ${GENERATED}
# syntax=docker/dockerfile:1

FROM node:22-alpine AS base
RUN corepack enable && corepack prepare pnpm@10.12.1 --activate
WORKDIR /app

FROM base AS deps
COPY package.json pnpm-lock.yaml ./
COPY patches ./patches
# Skip lifecycle scripts: postinstall (fumadocs-mdx) needs source.config.ts
RUN pnpm install --frozen-lockfile --ignore-scripts

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN pnpm rebuild && pnpm run postinstall
RUN ${buildCommand}

FROM base AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=${port}
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \\
	&& adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=builder /app/patches ./patches
COPY --from=builder /app/next.config.mjs ./next.config.mjs
COPY --from=builder /app/tsconfig.json ./tsconfig.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/migrations ./migrations
COPY --from=builder /app/scripts/db-migrate.mjs ./scripts/db-migrate.mjs
COPY --from=builder /app/drizzle.config.ts ./drizzle.config.ts
COPY --from=builder /app/src/database ./src/database

USER nextjs
EXPOSE ${port}

# Migrate at process start (needs DATABASE_URL), then serve Next.js
CMD ["sh", "-c", "${containerStartCommand}"]
`
}

function dockerignore(): string {
    return `# ${GENERATED}
node_modules
.next
.git
.env
.env.*
!.env.example
*.md
.cursor
.turbo
coverage
agent-transcripts
`
}

function dockerCompose(): string {
    const { name, port, dokploy } = deployConfig
    const router = dokploy.routerName
    const domain = dokploy.domain
    return `# ${GENERATED}
# Dokploy: Compose path ./docker-compose.yml — set dokploy.domain in deploy/config.ts then re-sync.

services:
  ${name}:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${port}"
    environment:
      - DATABASE_URL=\${DATABASE_URL}
      - BETTER_AUTH_SECRET=\${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=\${BETTER_AUTH_URL}
      - PORT=${port}
      - HOSTNAME=0.0.0.0
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${router}.rule=Host(\`${domain}\`)"
      - "traefik.http.routers.${router}.entrypoints=websecure"
      - "traefik.http.routers.${router}.tls.certResolver=letsencrypt"
      - "traefik.http.services.${router}.loadbalancer.server.port=${port}"

networks:
  dokploy-network:
    external: true
`
}

function railwayIac(): string {
    const {
        port,
        healthcheckPath,
        healthcheckTimeout,
        railway
    } = deployConfig
    return `// ${GENERATED}
// Railway Infrastructure as Code — plan/apply with the Railway CLI:
//   railway link && railway config plan && railway config apply
// Do not add railway.toml (Config as Code is deprecated).
import {
    defineRailway,
    github,
    group,
    postgres,
    preserve,
    project,
    redis,
    service
} from "railway/iac"

export default defineRailway(() => {
    const db = postgres("${railway.postgresName}")
    const cache = redis("${railway.redisName}")

    const app = service("${railway.serviceName}", {
        source: github("${railway.githubRepo}", { branch: "${railway.branch}" }),
        build: {
            builder: "DOCKERFILE",
            dockerfilePath: "Dockerfile",
            // Image build must not need DATABASE_URL (migrate runs in CMD).
            buildCommand: null
        },
        // Omit start — Dockerfile CMD runs \`pnpm start\` (migrate + next start).
        healthcheck: "${healthcheckPath}",
        healthcheckTimeout: ${healthcheckTimeout},
        deploy: {
            startCommand: null,
            sleepApplication: false,
            restartPolicyType: "ON_FAILURE",
            restartPolicyMaxRetries: 5,
            multiRegionConfig: {
                "${railway.region}": { numReplicas: 1 }
            }
        },
        env: {
            PORT: "${port}",
            DATABASE_URL: db.env.DATABASE_URL,
            REDIS_URL: cache.env.REDIS_URL,
            BETTER_AUTH_SECRET: preserve(),
            BETTER_AUTH_URL: preserve(),
            APPLICATION_NAME: preserve(),
            BETTER_AUTH_API_KEY: preserve(),
            BETTER_AUTH_IDENTIFY_URL: preserve(),
            NEXT_PUBLIC_ORGANIZATIONS_ENABLED: preserve()
        }
    })

    const backend = group("Backend", [db, cache, app])

    return project("${railway.projectName}", {
        resources: [backend]
    })
})
`

}

function railwayReadme(): string {
    return `# Railway Infrastructure as Code

This directory is generated by \`pnpm deploy:sync\` from \`deploy/config.ts\`.

## Commands

\`\`\`bash
railway link
railway config plan
railway config apply
\`\`\`

Edit knobs in \`deploy/config.ts\` (healthcheck path, port, GitHub repo, service names), then re-run \`pnpm deploy:sync\`. Do not revive \`railway.toml\` — Config as Code is deprecated.
`
}

function wranglerContainers(): string {
    const { name, cloudflare, requiredEnv } = deployConfig
    const className = cloudflare.containerClassName
    const secrets = requiredEnv.map((key) => `"${key}"`).join(", ")
    return `// ${GENERATED}
// Cloudflare runtime: containers (default)
{
	"$schema": "./node_modules/wrangler/config-schema.json",
	"name": "${name}",
	"main": "${cloudflare.containerWorker}",
	"compatibility_date": "2026-07-01",
	"compatibility_flags": ["nodejs_compat"],
	"containers": [
		{
			"class_name": "${className}",
			"image": "./Dockerfile",
			"instance_type": "${cloudflare.instanceType}",
			"max_instances": 3
		}
	],
	"durable_objects": {
		"bindings": [
			{
				"class_name": "${className}",
				"name": "AUTH_SERVER"
			}
		]
	},
	"migrations": [
		{
			"tag": "v1",
			"new_sqlite_classes": ["${className}"]
		}
	],
	"secrets": {
		"required": [${secrets}]
	},
	"observability": {
		"enabled": true
	}
}
`
}

function wranglerWorkers(): string {
    const { name } = deployConfig
    return `// ${GENERATED}
// Cloudflare runtime: workers (OpenNext)
// Install: pnpm add -D wrangler @opennextjs/cloudflare
// Postgres: configure Hyperdrive and bind it in this file (see docs/framework/deployment.mdx).
{
	"$schema": "./node_modules/wrangler/config-schema.json",
	"name": "${name}",
	"main": ".open-next/worker.js",
	"compatibility_date": "2026-07-01",
	"compatibility_flags": ["nodejs_compat"],
	"assets": {
		"directory": ".open-next/assets",
		"binding": "ASSETS"
	},
	"observability": {
		"enabled": true
	}
}
`
}

function openNextConfig(): string {
    return `// ${GENERATED}
// Used when deployConfig.cloudflare.runtime === "workers".
import { defineCloudflareConfig } from "@opennextjs/cloudflare"

export default defineCloudflareConfig()
`
}

function main() {
    write("Dockerfile", dockerfile())
    write(".dockerignore", dockerignore())
    write("docker-compose.yml", dockerCompose())
    write(".railway/railway.ts", railwayIac())
    write(".railway/README.md", railwayReadme())

    if (deployConfig.cloudflare.runtime === "workers") {
        write("wrangler.jsonc", wranglerWorkers())
        write("open-next.config.ts", openNextConfig())
    } else {
        write("wrangler.jsonc", wranglerContainers())
    }

    console.log(
        `\ndeploy sync complete (cloudflare.runtime=${deployConfig.cloudflare.runtime}; railway=.railway/railway.ts)`
    )
}

main()
