// Generated by `pnpm deploy:sync`. Edit `deploy/config.ts`, then re-run sync.
// Railway Infrastructure as Code — plan/apply with the Railway CLI:
//   railway link && railway config plan && railway config apply
// Do not add railway.toml (Config as Code is deprecated).
import {
    defineRailway,
    github,
    group,
    postgres,
    preserve,
    project,
    redis,
    service
} from "railway/iac"

export default defineRailway(() => {
    const db = postgres("Postgres")
    const cache = redis("Redis")

    const app = service("Better-Auth Server", {
        source: github("t3xydev/better-auth-server", { branch: "main" }),
        build: {
            builder: "DOCKERFILE",
            dockerfilePath: "Dockerfile",
            // Image build must not need DATABASE_URL (migrate runs in CMD).
            buildCommand: null
        },
        // Omit start — Dockerfile CMD runs `pnpm start` (migrate + next start).
        healthcheck: "/api/health",
        healthcheckTimeout: 300,
        deploy: {
            startCommand: null,
            sleepApplication: false,
            restartPolicyType: "ON_FAILURE",
            restartPolicyMaxRetries: 5,
            multiRegionConfig: {
                "us-east4-eqdc4a": { numReplicas: 1 }
            }
        },
        env: {
            PORT: "3000",
            DATABASE_URL: db.env.DATABASE_URL,
            REDIS_URL: cache.env.REDIS_URL,
            BETTER_AUTH_SECRET: preserve(),
            BETTER_AUTH_URL: preserve(),
            APPLICATION_NAME: preserve(),
            BETTER_AUTH_API_KEY: preserve(),
            BETTER_AUTH_IDENTIFY_URL: preserve(),
            NEXT_PUBLIC_ORGANIZATIONS_ENABLED: preserve()
        }
    })

    const backend = group("Backend", [db, cache, app])

    return project("BetterAuth StarterKit", {
        resources: [backend]
    })
})
