// Generated by `pnpm deploy:sync`. Edit `deploy/config.ts`, then re-run sync.
// Railway Infrastructure as Code — plan/apply with the Railway CLI:
//   railway link && railway config plan && railway config apply
// Do not add railway.toml (Config as Code is deprecated).
// App source is the GHCR image (ghcr.io/t3xydev/better-auth-server:latest). Releases from main move that tag.
import {
    defineRailway,
    group,
    image,
    postgres,
    preserve,
    project,
    redis,
    service
} from "railway/iac"

export default defineRailway(() => {
    const db = postgres("Postgres")
    const cache = redis("Redis")

    const app = service("Better-Auth Server", {
        source: image("ghcr.io/t3xydev/better-auth-server:latest"),
        // Omit start — image CMD runs `pnpm start` (migrate + next start).
        healthcheck: "/api/health",
        healthcheckTimeout: 300,
        deploy: {
            startCommand: null,
            sleepApplication: false,
            restartPolicyType: "ON_FAILURE",
            restartPolicyMaxRetries: 5,
            multiRegionConfig: {
                "us-east4-eqdc4a": { numReplicas: 1 }
            }
        },
        env: {
            // Do not set PORT — Railway injects it for healthchecks/public networking.
            DATABASE_URL: db.env.DATABASE_URL,
            REDIS_URL: cache.env.REDIS_URL,
            BETTER_AUTH_SECRET: preserve(),
            BETTER_AUTH_URL: preserve(),
            APPLICATION_NAME: preserve(),
            BETTER_AUTH_API_KEY: preserve(),
            BETTER_AUTH_IDENTIFY_URL: preserve(),
            NEXT_PUBLIC_ORGANIZATIONS_ENABLED: preserve(),
            NEXT_PUBLIC_BILLING_ENABLED: preserve(),
            BILLING_PROVIDER: preserve(),
            STRIPE_SECRET_KEY: preserve(),
            STRIPE_WEBHOOK_SECRET: preserve(),
            BILLING_STRIPE_PRICE_PREMIUM_MONTHLY: preserve(),
            BILLING_STRIPE_PRICE_PREMIUM_YEARLY: preserve(),
            BILLING_TRIAL_DAYS: preserve(),
            ZONELESS_API_KEY: preserve(),
            ZONELESS_API_URL: preserve(),
            ZONELESS_WEBHOOK_SECRET: preserve(),
            BILLING_ZONELESS_PRICE_PREMIUM_MONTHLY: preserve(),
            BILLING_ZONELESS_PRICE_PREMIUM_YEARLY: preserve()
        }
    })

    const backend = group("Backend", [db, cache, app])

    return project("BetterAuth Server", {
        resources: [backend]
    })
})
